

insert  into `categories`(`id`,`name`,`description`,`created_at`,`updated_at`) values 
(1,'Information Technology','Jobs related to software development, IT support, and technology services.',NULL,NULL),
(2,'Finance','Jobs in the finance and accounting sector.',NULL,NULL),
(3,'Marketing','Jobs related to marketing, advertising, and promotions.',NULL,NULL),
(4,'Healthcare','Jobs in the healthcare and medical field.',NULL,NULL),
(5,'Customer Service','Jobs focused on providing customer support and assistance.',NULL,NULL),
(6,'Building and Construction','Jobs in the construction industry',NULL,NULL),
(7,'Mechanics and Machinery','Jobs in the mechanics and machines industry',NULL,NULL),
(8,'Renewable Energy',NULL,NULL,NULL),
(9,'Beauty and Cosmetics',NULL,NULL,NULL),
(10,'Welding',NULL,NULL,NULL);


insert  into `skills`(`id`,`name`,`description`,`created_at`,`updated_at`) values 
(1,'Communication','',NULL,NULL),
(2,'Problem Solving','',NULL,NULL),
(3,'Critical Thinking','',NULL,NULL),
(4,'Leadership','',NULL,NULL),
(5,'Teamwork','',NULL,NULL),
(6,'Time Management','',NULL,NULL),
(7,'Adaptability','',NULL,NULL),
(8,'Creativity','',NULL,NULL),
(9,'Negotiation','',NULL,NULL),
(10,'Conflict Resolution','',NULL,NULL),
(11,'Public Speaking','',NULL,NULL),
(12,'Customer Service','',NULL,NULL),
(13,'Sales','',NULL,NULL),
(14,'Marketing','',NULL,NULL),
(15,'Content Writing','',NULL,NULL),
(16,'Digital Marketing','',NULL,NULL),
(17,'Financial Analysis','',NULL,NULL),
(18,'Photography','',NULL,NULL),
(19,'Video Production','',NULL,NULL),
(20,'Foreign Languages','',NULL,NULL),
(21,'Legal Research','',NULL,NULL),
(22,'Medical Research','',NULL,NULL),
(23,'Teaching','',NULL,NULL),
(24,'Carpentry','',NULL,NULL),
(25,'Plumbing','',NULL,NULL),
(26,'Mechanical Repair','',NULL,NULL),
(27,'Gardening','',NULL,NULL),
(28,'Cooking','',NULL,NULL),
(29,'Yoga','',NULL,NULL),
(30,'Meditation','',NULL,NULL),
(31,'JavaScript','',NULL,NULL),
(32,'Python','',NULL,NULL),
(33,'Java','',NULL,NULL),
(34,'C++','',NULL,NULL),
(35,'Ruby','',NULL,NULL),
(36,'PHP','',NULL,NULL),
(37,'Swift','',NULL,NULL),
(38,'SQL','',NULL,NULL),
(39,'HTML','',NULL,NULL),
(40,'CSS','',NULL,NULL),
(41,'C#','',NULL,NULL),
(42,'React','',NULL,NULL),
(43,'Angular','',NULL,NULL),
(44,'Vue.js','',NULL,NULL),
(45,'Node.js','',NULL,NULL),
(46,'Django','',NULL,NULL),
(47,'Ruby on Rails','',NULL,NULL),
(48,'Go','',NULL,NULL),
(49,'Rust','',NULL,NULL),
(50,'SwiftUI','',NULL,NULL),
(51,'Kotlin','',NULL,NULL),
(52,'Perl','',NULL,NULL),
(53,'TypeScript','',NULL,NULL),
(54,'Redux','',NULL,NULL),
(55,'MongoDB','',NULL,NULL),
(56,'MySQL','',NULL,NULL),
(57,'PostgreSQL','',NULL,NULL),
(58,'Firebase','',NULL,NULL),
(59,'Unity','',NULL,NULL),
(60,'Machine Learning','',NULL,NULL),
(61,'Artificial Intelligence','',NULL,NULL),
(62,'Data Analysis','',NULL,NULL),
(63,'DevOps','',NULL,NULL),
(64,'Blockchain','',NULL,NULL),
(65,'Cloud Computing','',NULL,NULL),
(66,'UI/UX Design','',NULL,NULL),
(67,'Graphic Design','',NULL,NULL),
(68,'Video Editing','',NULL,NULL),
(69,'Project Management','',NULL,NULL),
(70,'Customer Support','',NULL,NULL),
(71,'Social Media Management','',NULL,NULL),
(72,'Event Planning','',NULL,NULL),
(73,'Interior Design','',NULL,NULL),
(74,'Fashion Design','',NULL,NULL),
(75,'Illustration','',NULL,NULL),
(76,'Digital Illustration','',NULL,NULL),
(77,'Business Analysis','',NULL,NULL),
(78,'Quality Assurance','',NULL,NULL),
(79,'Database Management','',NULL,NULL),
(80,'Data Entry','',NULL,NULL),
(81,'E-commerce','',NULL,NULL),
(82,'Inventory Management','',NULL,NULL),
(83,'Human Resources','',NULL,NULL),
(84,'Project Coordination','',NULL,NULL),
(85,'Public Relations','',NULL,NULL),
(86,'Sculpture','',NULL,NULL),
(87,'Woodworking','',NULL,NULL),
(88,'Electrical Engineering','',NULL,NULL),
(89,'Nursing','',NULL,NULL),
(90,'Physical Therapy','',NULL,NULL),
(91,'Animation','',NULL,NULL),
(92,'3D Modeling','',NULL,NULL),
(93,'Cybersecurity','',NULL,NULL),
(94,'Network Administration','',NULL,NULL),
(95,'Risk Management','',NULL,NULL),
(96,'Forensic Accounting','',NULL,NULL),
(97,'Environmental Science','',NULL,NULL),
(98,'Astronomy','',NULL,NULL),
(99,'Fashion Photography','',NULL,NULL);
